### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'set')

### ISSUE THREAD

**Issue by zjy365** [uiwjs/react-codemirror#568] opened 2023-09-19 06:51 UTC
## Here's how I use it
```
            <CodeMirror
              extensions={[StreamLanguage.define(yaml)]}
              width="100%"
              height="100%"
              minHeight="1200px"
              onChange={debounce(onYamlChange, 1000)}
            />
```
## my version
```
    "@codemirror/language": "^6.8.0",
    "@codemirror/legacy-modes": "^6.3.3",
    "@emotion/react": "^11.10.6",
    "@emotion/styled": "^11.10.6",
    "@kubernetes/client-node": "^0.18.1",
    "@next/font": "13.1.6",
    "@tanstack/react-query": "^4.24.10",
    "@uiw/react-codemirror": "^4.21.9",
```

## When I mouseover this editor section, the console output is consistent. this error
<img width="572" alt="image" src="https://github.com/uiwjs/react-codemirror/assets/72259332/af3bf040-65af-4bdd-82cf-bcfef6672b47">

**Comment by jaywcjlove** [comment] 2023-09-19 07:16
@zjy365 Can you provide me with a reproducible example using [https://codesandbox.io](https://codesandbox.io/embed/react-codemirror-example-codemirror-6-slvju?fontsize=14&hidenavigation=1&theme=dark)? I can help you troubleshoot the issue.

**Comment by zjy365** [comment] 2023-09-19 08:10
@jaywcjlove  I created a new next project and tried it. You can take a look.
https://codesandbox.io/p/sandbox/xenodochial-robinson-9yfw8c

**Comment by jaywcjlove** [comment] 2023-09-19 08:58
<img width="1465" alt="image" src="https://github.com/uiwjs/react-codemirror/assets/1680273/60beeff0-ac49-4079-95ee-51a7b2876f1d">


There are no errors when downloading the project locally.

<img width="1098" alt="image" src="https://github.com/uiwjs/react-codemirror/assets/1680273/955cac78-0a73-44c3-a4c6-04037b07f9ea">

<img width="767" alt="image" src="https://github.com/uiwjs/react-codemirror/assets/1680273/637e8bf2-d4a0-4c53-8e58-884b0f7472e5">


@zjy365 So, I cannot reproduce your error.

**Comment by noa24** [comment] 2023-09-19 12:13
i also have the same issue

**Comment by zjy365** [comment] 2023-09-19 13:28
I think if you need to move the mouse in this area to trigger mousemove, or enter content into the editor, the above error will be triggered.

<img width="1302" alt="image" src="https://github.com/uiwjs/react-codemirror/assets/72259332/87ec829a-50f7-4d15-bf65-237ba8bb1c51">

@jaywcjlove

**Comment by codercoin98** [comment] 2023-09-20 01:47
i have the same issuse☹️

**Comment by jaywcjlove** [comment] 2023-09-20 02:34
https://github.com/uiwjs/react-codemirror/assets/1680273/c1b29a5a-1a1d-4b90-b2d2-61202adccf9b

I recreated the nextjs project and the error disappeared.

@codercoin98  @zjy365 @noa24

**Comment by se1phine** [comment] 2023-09-20 10:04
![image](https://github.com/uiwjs/react-codemirror/assets/11831722/e3ef2519-ad2a-4c46-80e3-3e6c8e57ee20)

**Comment by liaoyingtao** [comment] 2023-09-20 10:59
i have the same issuse too, only set the onChange props will show

**Comment by liaoyingtao** [comment] 2023-09-20 11:05
![image](https://github.com/uiwjs/react-codemirror/assets/22324208/e2677ae1-a9fa-47b9-bf76-b1855d19bf81)
https://uiwjs.github.io/react-codemirror/#/theme/data/copilot
the demo has same error

**Comment by kohloth** [comment] 2023-09-21 00:18
I am having this same issue too. It seemed to start happening recently (I think) but downgrading the version number does not seem to have fixed the problem. These errors come up when moving the mouse over the code mirror input and when pressing keys inside of it. I've tried to see if I can make the error go away by simplifying my use of the component, but even after stripping it down to the bare minimum props (shown below) I still see these console errors.

My usage of the component (note that I've commented most props out - errors still occur)

```tsx
	<CodeMirror
		ref={rootRef}
		// indentWithTab={false}
		// readOnly={usedReadOnly}
		className="code-input__input"
		// theme={theme}
		value={value}
		height="100%"
		// extensions={extensions}
		onChange={handleChange}
		// basicSetup={basicSetup}
	/>
```

Error is the same as the others have reported:

![Screenshot from 2023-09-21 01-18-18](https://github.com/uiwjs/react-codemirror/assets/1596204/a766ffc6-ed13-41c6-9db9-8f866cf4332e)

**Comment by jaywcjlove** [comment] 2023-09-21 02:52
@zjy365 @kohloth @liaoyingtao  This is caused by the integrated `crosshairCursor` Extension. I have already set it to `false` by default.


Upgrading to `v4.21.15` or using the following configuration can suppress the error caused by the `crosshairCursor`. The issue related to crosshairCursor needs to be resolved by the @codemirror team.

```diff
<CodeMirror 
  basicSetup={{
+   crosshairCursor: false
  }}
 />
```

**Comment by mojiAh** [comment] 2023-09-21 11:29
Had same issue, for now setting the `crosshairCursor: false` fixed the issue.

**Comment by zjy365** [comment] 2023-09-22 02:22
> @zjy365 @kohloth @liaoyingtao This is caused by the integrated `crosshairCursor` Extension. I have already set it to `false` by default.
> 
> Upgrading to `v4.21.15` or using the following configuration can suppress the error caused by the `crosshairCursor`. The issue related to crosshairCursor needs to be resolved by the @codemirror team.
> 
> ```diff
> <CodeMirror 
>   basicSetup={{
> +   crosshairCursor: false
>   }}
>  />
> ```

Thank you. Successfully resolved

**Closed** 2023-09-22 02:22 UTC
